# Trigger the workflow on push or pull request
on: [push, pull_request]

name: Build
jobs:
  build-1:
    name: Build with minimal options
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build with the latest action rev
      uses: shalzz/zola-deploy-action@master
      env:
        BUILD_ONLY: true
        BUILD_DIR: test-site
  build-2:
    name: Build with BUILD_FLAGS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build with the latest action rev
      uses: shalzz/zola-deploy-action@master
      env:
        BUILD_ONLY: true
        BUILD_DIR: test-site
        BUILD_FLAGS: --drafts --base-url example.com
