# Trigger the workflow on push or pull request
on: [push, pull_request]

name: Build
jobs:
  build-1:
    name: Build with minimal options
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build with the latest action rev
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: build-test-1
        BUILD_DIR: test-site
        TOKEN: ${{ secrets.TOKEN }}
  build-2:
    name: Build with BUILD_FLAGS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build with the latest action rev
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: build-test-2
        BUILD_DIR: test-site
        BUILD_FLAGS: --drafts --base-url example.com
        TOKEN: ${{ secrets.TOKEN }}
  build-3:
    name: Build and skip deploy 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build only with the latest action rev.
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: build-test-3
        BUILD_DIR: test-site
        TOKEN: ${{ secrets.TOKEN }}
        BUILD_ONLY: true
